#!/usr/bin/env python3
# Copyright 2025 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Gemini 2.5 Pro

import json
import os
import sys
import tempfile
from urllib.parse import urlparse

from gz.math import AxisAlignedBox

# Gazebo API imports
from gz.sim import K_NULL_ENTITY, Link, Model, TestFixture, World, world_entity


def get_model_name_from_uri(uri: str) -> str:
    """Extract a model name from a Gazebo Fuel URI."""
    try:
        path = urlparse(uri).path
        model_name = os.path.basename(path)
        if not model_name:
            raise ValueError('Could not parse model name from URI')
        return model_name
    except Exception as e:
        print(f'Error: Invalid model URI provided: {uri}. {e}', file=sys.stderr)
        return ''


def generate_world_sdf(model_uris: list) -> str:
    """
    Generate a single world SDF string that includes all specified models.

    The models are spaced out to prevent initial collisions.
    """
    include_tags = []
    # Space models 1 meters apart along the x-axis.
    spacing = 1.0
    for i, uri in enumerate(model_uris):
        model_name = get_model_name_from_uri(uri)
        if model_name:
            pose = f'{i * spacing} 0 0 0 0 0'
            include_tags.append(f"""
            <include>
              <name>{model_name}</name>
              <uri>{uri}</uri>
              <pose>{pose}</pose>
            </include>""")

    return f"""\
<?xml version="1.0" ?>
<sdf version='1.7'>
    <world name='bounding_box_world'>
    {''.join(include_tags)}
    </world>
</sdf>
    """


def main():
    """Calculate and print bounding boxes for a list of models."""
    model_uris = [
        'https://fuel.gazebosim.org/1.0/OpenRobotics/models/Lidar 2d v2',
        'https://fuel.gazebosim.org/1.0/OpenRobotics/models/Lidar 3d v1',
    ]

    model_names = [get_model_name_from_uri(uri) for uri in model_uris if uri]
    model_name_to_uri = dict(zip(model_names, model_uris, strict=False))

    world_sdf_string = generate_world_sdf(model_uris)
    print(world_sdf_string)

    world_file = None
    try:
        with tempfile.NamedTemporaryFile(
            mode='w', delete=False, suffix='.sdf', encoding='utf-8'
        ) as f:
            f.write(world_sdf_string)
            world_file = f.name

        fixture = TestFixture(world_file)

        results = {}
        iteration_count = 0
        setup_complete = False

        def on_pre_update(info, ecm):
            """
            Enable bounding box checks for all links on all models.

            This only needs to run once after the models are spawned.
            """
            nonlocal setup_complete
            if setup_complete:
                return

            world_entity_val = world_entity(ecm)
            if world_entity_val == K_NULL_ENTITY:
                return

            world = World(world_entity_val)

            # Wait until all expected models are loaded into the simulation.
            if world.model_count(ecm) < len(model_names):
                return

            model_entities = world.models(ecm)
            for model_entity in model_entities:
                model = Model(model_entity)
                if not model.valid(ecm):
                    continue
                for link_entity in model.links(ecm):
                    link = Link(link_entity)
                    if link.valid(ecm):
                        link.enable_bounding_box_checks(ecm, True)

            setup_complete = True

        def on_post_update(info, ecm):
            """After physics has run, read the final world-axis-aligned bounding box."""
            nonlocal iteration_count

            if not setup_complete:
                return

            # Stop once we've found all models or after a timeout.
            if len(results) == len(model_names) or iteration_count > 50:
                return
            iteration_count += 1

            world_entity_val = world_entity(ecm)
            if world_entity_val == K_NULL_ENTITY:
                return
            world = World(world_entity_val)

            for model_entity in world.models(ecm):
                model = Model(model_entity)
                if not model.valid(ecm):
                    continue

                model_name = model.name(ecm)

                if model_name in results or model_name not in model_names:
                    continue

                combined_box = AxisAlignedBox()
                found_at_least_one_link = False

                for link_entity in model.links(ecm):
                    link = Link(link_entity)
                    if link.valid(ecm):
                        link_box = link.world_axis_aligned_box(ecm)
                        if link_box and (
                            link_box.volume() > 1e-9 or link_box.min() != link_box.max()
                        ):
                            if not found_at_least_one_link:
                                combined_box = link_box
                            else:
                                combined_box += link_box
                            found_at_least_one_link = True

                if found_at_least_one_link:
                    results[model_name] = combined_box

        fixture.on_pre_update(on_pre_update)
        fixture.on_post_update(on_post_update)
        fixture.finalize()
        fixture.server().run(True, 60, False)

        json_output = []

        # Print results
        print('--- Bounding Box Calculation Results ---')
        for name in model_names:
            data = {'uri': model_name_to_uri[name]}
            print(f'\nModel: {name}')
            if name in results:
                bbox = results[name]
                # print(f"  -> Bounding Box Min: {bbox.min()}")
                # print(f"  -> Bounding Box Max: {bbox.max()}")
                # print(f"  -> Bounding Box Center: {bbox.center()}")
                # print(f"  -> Bounding Box Size: {bbox.size()}")
                size = bbox.size()
                data['size'] = [size.x(), size.y(), size.z()]
                json_output.append(data)
            else:
                print('  -> Failed to determine bounding box.')
        print(json.dumps(json_output))

    finally:
        if world_file and os.path.exists(world_file):
            os.remove(world_file)


if __name__ == '__main__':
    os.environ['GZ_LOG_LEVEL'] = '3'
    main()
