# Copyright 2024
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Gemini 2.5 Pro

import math
import random
import time

import rclpy
from rclpy.node import Node

from geometry_msgs.msg import Point, Pose, PoseStamped, Quaternion, Twist, Vector3
from simulation_interfaces.msg import EntityState, Resource, Result
from simulation_interfaces.srv import (
    GetEntityState, ResetSimulation, SetEntityState, SpawnEntity
)

# A list of objects to be spawned, including their Gazebo Fuel URI and bounding box size.
# The size is now used to ensure proper placement on the tray.
OBJECTS_TO_SPAWN = [
    {
        "uri": "https://fuel.gazebosim.org/1.0/GoogleResearch/models/Weisshai_Great_White_Shark",
        "size": (0.143696, 0.167077, 0.074769)
    },
    {
        "uri": "https://fuel.gazebosim.org/1.0/GoogleResearch/models/Vtech_Roll_Learn_Turtle",
        "size": (0.169432, 0.232494, 0.117513)
    },
    {
        "uri": "https://fuel.gazebosim.org/1.0/GoogleResearch/models/Ubisoft_RockSmith_Real_Tone_Cable_Xbox_30",
        "size": (0.171647, 0.140048, 0.043601)
    },
    {
        "uri": "https://fuel.gazebosim.org/1.0/GoogleResearch/models/Dino_3",
        "size": (0.288729, 0.06852, 0.127241)
    },
    {
        "uri": "https://fuel.gazebosim.org/1.0/GoogleResearch/models/Dino_4",
        "size": (0.136815, 0.058722, 0.092725)
    },
]

class ConveyorController(Node):
    """
    A ROS 2 node to control a conveyor belt scenario in Gazebo.

    This node orchestrates a repeating cycle in a synchronous manner:
    1. Resets the simulation.
    2. Spawns a random number of objects onto a tray.
    3. Moves the tray along a conveyor belt by setting its velocity.
    4. Monitors the tray's position and stops it at a designated inspection point.
    5. Waits for a configurable duration.
    6. Repeats the cycle.
    """

    def __init__(self):
        super().__init__('conveyor_controller')

        self.declare_parameters(
            namespace='',
            parameters=[
                ('inspection_time', 5.0),
                ('tray_speed', 0.25),
                ('inspection_x_position', 2.0),
                ('tray_name', 'tray'),
                ('num_objects_to_spawn', 4),
                ('tray_width', 0.4),
                ('tray_depth', 0.5),
            ]
        )

        # Create clients for the required simulation services
        self._spawn_client = self.create_client(SpawnEntity, '/gzserver/spawn_entity')
        self._set_state_client = self.create_client(SetEntityState, '/gzserver/set_entity_state')
        self._get_state_client = self.create_client(GetEntityState, '/gzserver/get_entity_state')
        self._reset_sim_client = self.create_client(ResetSimulation, '/gzserver/reset_simulation')
        self.spawned_object_names = []

        self.wait_for_services()

    def wait_for_services(self):
        """Blocks until all required simulation services are available."""
        self.get_logger().info('Waiting for simulation services...')
        services = {
            'spawn': self._spawn_client,
            'set_state': self._set_state_client,
            'get_state': self._get_state_client,
            'reset': self._reset_sim_client
        }
        for name, client in services.items():
            while not client.wait_for_service(timeout_sec=1.0):
                self.get_logger().warning(f'Service "{name}" not available, waiting again...')
        self.get_logger().info('All simulation services are available.')

    def run_full_cycle(self):
        """
        Runs one complete simulation cycle synchronously.
        """
        self.get_logger().info('--- Starting new conveyor cycle ---')
        try:
            # 1. Reset the simulation to a clean state
            self.reset_simulation()
            time.sleep(1.0) # Give the simulator time to settle

            # 2. Spawn a random selection of objects
            self.spawn_objects()
            time.sleep(10.5)

            # # 3. Start moving the tray
            # self.set_tray_velocity(is_moving=True)
            #
            # # 4. Monitor the tray until it reaches the inspection point
            # self.monitor_tray_position()

            # 5. Stop the tray for inspection
            self.set_tray_velocity(is_moving=False)
            inspection_time = self.get_parameter('inspection_time').get_parameter_value().double_value
            self.get_logger().info(f"Waiting for {inspection_time} seconds for inspection...")
            time.sleep(inspection_time)

        except (RuntimeError, KeyboardInterrupt) as e:
            self.get_logger().error(f"An error occurred during the cycle: {e}")
            self.get_logger().info("Shutting down node.")
            raise e # Re-raise to stop the main loop
        except Exception as e:
            self.get_logger().error(f"An unexpected error occurred: {e}")
            self.get_logger().info("Attempting a new cycle after a delay...")
            time.sleep(5.0)

    def reset_simulation(self):
        """Calls the reset_simulation service."""
        request = ResetSimulation.Request()
        request.scope = ResetSimulation.Request.SCOPE_ALL
        self.get_logger().info('Resetting simulation...')
        
        future = self._reset_sim_client.call_async(request)
        rclpy.spin_until_future_complete(self, future)
        
        response_raw = future.result()
        if response_raw is None:
            error_msg = "Failed to get response from reset_simulation service."
            self.get_logger().error(error_msg)
            raise RuntimeError(error_msg)
        response: ResetSimulation.Response = response_raw

        if response.result.result != Result.RESULT_OK:
            error_msg = f"Failed to reset simulation: {response.result.error_message}"
            self.get_logger().error(error_msg)
            raise RuntimeError(error_msg)
        
        self.spawned_object_names.clear()
        self.get_logger().info('Simulation reset successfully.')

    def _is_overlapping(self, pos1, size1, pos2, size2):
        """Checks if two axis-aligned bounding boxes overlap in 2D (x, y)."""
        x1, y1 = pos1
        w1, d1 = size1
        x2, y2 = pos2
        w2, d2 = size2
        if abs(x1 - x2) * 2 >= (w1 + w2): return False
        if abs(y1 - y2) * 2 >= (d1 + d2): return False
        return True

    def get_tray_pose(self) -> Pose:
        """Gets the current pose of the tray in the world frame."""
        tray_name = self.get_parameter('tray_name').value
        request = GetEntityState.Request(entity=tray_name)
        
        future = self._get_state_client.call_async(request)
        rclpy.spin_until_future_complete(self, future)

        response_raw = future.result()
        if response_raw is None:
            error_msg = f"Failed to get response from get_entity_state for '{tray_name}'."
            self.get_logger().error(error_msg)
            raise RuntimeError(error_msg)
        response: GetEntityState.Response = response_raw

        if response.result.result == Result.RESULT_OK:
            return response.state.pose
        else:
            error_msg = f"Could not get pose for '{tray_name}': {response.result.error_message}"
            self.get_logger().error(error_msg)
            raise RuntimeError(error_msg)

    def spawn_objects(self):
        """
        Spawns objects onto the tray, ensuring they are within bounds and do not overlap.
        """
        num_objects = self.get_parameter('num_objects_to_spawn').value
        tray_width = self.get_parameter('tray_width').value
        tray_depth = self.get_parameter('tray_depth').value
        self.get_logger().info(f"Attempting to spawn {num_objects} objects...")

        # Get the tray's pose in the world frame to calculate absolute spawn coordinates
        tray_pose = self.get_tray_pose()
        
        placed_objects = []
        MAX_PLACEMENT_ATTEMPTS = 20

        for i in range(num_objects):
            is_placed = False
            for _ in range(MAX_PLACEMENT_ATTEMPTS):
                object_to_spawn = random.choice(OBJECTS_TO_SPAWN)
                obj_size_x, obj_size_y, _ = object_to_spawn["size"]
                
                half_x = obj_size_x / 2.0; half_y = obj_size_y / 2.0
                spawn_range_x = (tray_width / 2.0) - half_x
                spawn_range_y = (tray_depth / 2.0) - half_y
                
                # Relative position on the tray
                relative_pos_x = random.uniform(-spawn_range_x, spawn_range_x)
                relative_pos_y = random.uniform(-spawn_range_y, spawn_range_y)
                
                current_pos = (relative_pos_x, relative_pos_y)
                current_size = (obj_size_x, obj_size_y)
                has_collision = any(self._is_overlapping(current_pos, current_size, p['pos'], p['size']) for p in placed_objects)
                
                if not has_collision:
                    object_name = f"spawned_object_{i}"
                    yaw = random.uniform(0, 2 * math.pi)
                    quat = self.yaw_to_quaternion(yaw)
                    
                    # Calculate absolute world coordinates
                    world_x = tray_pose.position.x + relative_pos_x
                    world_y = tray_pose.position.y + relative_pos_y
                    world_z = tray_pose.position.z + 0.2

                    # Create the request using the new message definition
                    request = SpawnEntity.Request()
                    request.name = object_name
                    request.allow_renaming = True
                    request.entity_resource = Resource(uri=object_to_spawn["uri"])
                    
                    # Set the initial pose in the world frame
                    pose_stamped = PoseStamped()
                    pose_stamped.header.frame_id = "" # Empty means world frame
                    pose_stamped.pose = Pose(position=Point(x=world_x, y=world_y, z=world_z), orientation=quat)
                    request.initial_pose = pose_stamped

                    self.get_logger().info(f"Spawning '{object_name}' in world at ({world_x:.2f}, {world_y:.2f})")
                    future = self._spawn_client.call_async(request)
                    rclpy.spin_until_future_complete(self, future)
                    
                    response_raw = future.result()
                    if response_raw is None:
                        self.get_logger().error(f"Failed to get response from spawn_entity service for '{object_name}'.")
                        continue
                    response: SpawnEntity.Response = response_raw

                    if response.result.result == Result.RESULT_OK:
                        self.get_logger().info(f"Successfully spawned entity with name: {response.entity_name}")
                        placed_objects.append({'pos': current_pos, 'size': current_size})
                        self.spawned_object_names.append(response.entity_name)
                        is_placed = True
                        break
                    else:
                        self.get_logger().error(f"Failed to spawn '{object_name}': {response.result.error_message}")
            
            if not is_placed:
                self.get_logger().warning(f"Could not place object {i+1}, skipping.")

    def set_tray_velocity(self, is_moving: bool):
        """Sets the linear velocity of the tray."""
        tray_name = self.get_parameter('tray_name').value
        speed = self.get_parameter('tray_speed').value
        request = SetEntityState.Request()
        request.entity = tray_name
        
        linear_velocity = Vector3()
        if is_moving:
            self.get_logger().info(f"Moving '{tray_name}' with speed {speed} m/s.")
            linear_velocity.x = speed
        else:
            self.get_logger().info(f"Stopping '{tray_name}'.")
            linear_velocity.x = 0.0
        
        request.state = EntityState(twist=Twist(linear=linear_velocity))

        future = self._set_state_client.call_async(request)
        rclpy.spin_until_future_complete(self, future)

        response_raw = future.result()
        if response_raw is None:
            error_msg = "Failed to get response from set_entity_state service."
            self.get_logger().error(error_msg)
            raise RuntimeError(error_msg)
        response: SetEntityState.Response = response_raw

        if response.result.result != Result.RESULT_OK:
            error_msg = f"Failed to set tray velocity: {response.result.error_message}"
            self.get_logger().error(error_msg)
            raise RuntimeError(error_msg)

    def monitor_tray_position(self):
        """Synchronously polls the tray's position until it reaches the target."""
        tray_name = self.get_parameter('tray_name').value
        inspection_x = self.get_parameter('inspection_x_position').value
        self.get_logger().info(f"Monitoring '{tray_name}' until it reaches x={inspection_x}...")

        while rclpy.ok():
            request = GetEntityState.Request(entity=tray_name)
            future = self._get_state_client.call_async(request)
            rclpy.spin_until_future_complete(self, future)

            response_raw = future.result()
            if response_raw is None:
                self.get_logger().warning(f"Failed to get response from get_entity_state for '{tray_name}'.")
                break
            response: GetEntityState.Response = response_raw

            if response and response.result.result == Result.RESULT_OK:
                current_x = response.state.pose.position.x
                if current_x >= inspection_x:
                    self.get_logger().info(f"Tray has reached inspection point at x={current_x:.2f}.")
                    break
            elif response:
                self.get_logger().warning(f"Failed to get state for '{tray_name}': {response.result.error_message}")
                break
            
            time.sleep(0.1)

    @staticmethod
    def yaw_to_quaternion(yaw: float) -> Quaternion:
        """Converts a yaw angle (in radians) to a quaternion."""
        return Quaternion(x=0.0, y=0.0, z=math.sin(yaw / 2.0), w=math.cos(yaw / 2.0))

def main(args=None):
    rclpy.init(args=args)
    conveyor_controller = None
    try:
        conveyor_controller = ConveyorController()
        while rclpy.ok():
            conveyor_controller.run_full_cycle()
    except (KeyboardInterrupt, RuntimeError):
        print("\nShutting down conveyor controller.")
    finally:
        if conveyor_controller:
            conveyor_controller.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()

if __name__ == '__main__':
    main()

